#### Given an mxn matrix. Write a program to carry out Gaussian elimination.
Report the following:
1. The resultant matrix.
2. the indexes of the columns that have pivots.

In [1]:
import numpy as np

def gaussian_elemination(a,b):
    # length of the system of equations
    n = len(a)

    # Elimination
    # k specifies the fixed rows that is the pivots from 0 to n-2
    for k in range(n-1):

        # Checks if pivot is very close to zero
        if abs(a[k,k])<1.0e-12:
            # Loop to find a row with a larger element in the same column to swap with
            for i in range (k+1,n):
                if np.fabs(a[i,k])>np.fabs(a[k,k]):
                    # Swapping rows k and i
                    a[[k,i]]=a[[i,k]]
                    b[[k,i]]=b[[i,k]]
                    break
        # i is used to apply elemination below the fixed rows from k+1 to n-1
        for i in range(k+1,n):
            # checks if first element is zero and skip to next iteration of i
            if a[i,k]==0:
                continue
                
            # calculates factor of a[k,k]/a[i,k]
            factor=a[k,k]/a[i,k]
            
            # updates element of Matrix A,each of the correspoding columns from k to n-1
            for j in range (k,n):
                a[i,j]=a[k,j]-a[i,j]*factor

            # Updates element of B from k to n-1
            b[i]=b[k]-b[i]*factor
            
    # Backward substitution
    # Solution vector
    x = [0.0]*n
    # Calculation of last variable
    x[n-1]=b[n-1]/a[n-1,n-1]
    
    # Iterates through the remaining variables in reverse order
    for i in range(n-2,-1,-1):
        sum_ax=0
        # Computes the sum of products for variable x[i]
        for j in range(i+1,n):
            sum_ax +=a[i,j]*x[j]
        # Compute the value of variable x[i]
        x[i]=(b[i]-sum_ax)/a[i,i]
            
    return a,x

def pivots(a):
    pivots=[]
    for i in range(rows):
        if a[i,i]!=0:
            pivots.append(i)
    return pivots

# User prompt number of rows
rows = int(input('Enter the number of rows:'))

# User prompt elements for matrix of mentioned size
print('Enter elements of matrix:')
a = np.array([[float(element) for element in input ().split()] for i in range(rows)])

print('Enter elements of B column:')
b = np.array([float(element) for element in input ().split()])

result1,result2=gaussian_elemination(a,b)
print(f'Resultant matrix is:\n{result1}\nSolution is:\n{result2}')
print(f'Pivot indexes are:\n{pivots(result1)}')



Enter the number of rows: 3


Enter elements of matrix:


 2 3 4
 9 7 6
 2 1 5


Enter elements of B column:


 5 1 8


Resultant matrix is:
[[2.         3.         4.        ]
 [0.         1.44444444 2.66666667]
 [0.         0.         3.38888889]]
Solution is:
[-0.8852459016393439, -0.4754098360655737, 2.0491803278688523]
Pivot indexes are:
[0, 1, 2]


####  Grahm-Schmidt in algorithms
Given n vectors, each having n components, write an algorithm that will orthogonalize these to make n
orthogonal vectors from these vectors using the Grahm-Schmidt procedure.

In [2]:
# Gram schmedit procedure

import numpy as np

# Function to perform Gram-Schmidt procedure using orthonormal and orthogonal functions
def Grahm_Schmidt_procedure(*v,n):
    # Function call orthonromal_basis
    result2=orthonromal_basis(*v,n=n)


# Function calculates orthonormal basis
def orthonromal_basis(*v,n):
    
    # orthogonal basis function call to calculate orthogonal basis
    result1=orthogonal_basis(*v,n=n)

    # Initialize list to store orthonormal basis
    N=[]
    print('\nOrthonormal basis of given vectors are:')

    # Iterate over the orthogonal vectors
    for i,q_i in enumerate(result1):

        # Calculate orthonormal vector
        N_i=q_i/np.sqrt(np.dot(q_i,q_i))

        # Appending orthonormal vectors to the list
        N.append(N_i)
        # Displaying the orthonormal vectors
        print(f'N{i + 1} is:\n{N_i}')
    return N


# Fuction calculates orthogonal basis 
def orthogonal_basis(*v,n):

    # Initialzie list to store orthogonal basis
    q=[v[0]]
    print(f'\nOrthogonl basis of given vectors are:\nq1 is:\n{q[0]}')

    # Iterarte over the other vectors
    for i in range(1, n):

        # Initialize a zero vector to store the projections 
        sum = [0]*n

        # Iterates over the orthogonal basis and given vectors
        for j in range(i):
            
            # Dot product of orthogonal basis
            dot_product_of_qi_qi = np.dot(q[j], q[j])
            # Dot product of orthogonal basis vectors and corresponding vector
            dot_product_of_qi_v = np.dot(v[i], q[j]) 
            # Scalar multiple of  above two
            scalar = dot_product_of_qi_v/dot_product_of_qi_qi 
            # Summation of the projections
            sum+= scalar * q[j]
        
        # Computing the orthogonal vectors 
        q_i = v[i] - sum
        # Appending the orthogonal vectors to the list
        q.append(q_i)
        # Displaying the current orthogonal vector
        print(f'q{i + 1} is:\n{q_i}')
            
    return q


# Initialize empty list to store append differernt vectors
vector=[]

# User prompt number of vectors
n=int(input('Enter the number of vectors:'))

# User prompt for elements of matrix
for i in range(n):
    print(f'Enter the elements of vector {i + 1}:')
    v=np.array([float(element) for element in input().split()])
    vector.append(v)
# Function call to perform Grahm Schmidt procedure
Grahm_Schmidt_procedure(*vector,n=n)

Enter the number of vectors: 3


Enter the elements of vector 1:


 2 3 4


Enter the elements of vector 2:


 9 7 6


Enter the elements of vector 3:


 2 1 5



Orthogonl basis of given vectors are:
q1 is:
[2. 3. 4.]
q2 is:
[ 4.65517241  0.48275862 -2.68965517]
q3 is:
[ 0.72189349 -1.73254438  0.93846154]

Orthonormal basis of given vectors are:
N1 is:
[0.37139068 0.55708601 0.74278135]
N2 is:
[ 0.86239537  0.08943359 -0.49827288]
N3 is:
[ 0.34401046 -0.8256251   0.4472136 ]


#### Finding Deteminant through recursion
Given a nxn matrix, determine its determinant using python programming. Write a recursive cod

In [5]:
# Function determinant computes the determinant of matrix
def determinant(matrix):
    n=len(matrix)
    # Base condition, if matrix is 1x1 return element
    if(n==1):
        return matrix[0][0]
    else:
        # Initialze sign for cofactor expansion 
        sign=1

        # Initialize determinant as zero
        det=0

        # Iteration through columns
        for col in range(n):
            sub_matrix=[] # Initialize sub matrix for storing (n-1)x(n-1) matrix

            # Iteration over each row of the matrix from the second row
            for row in range(1,n):
                sub_row=[] # Initialize sub-row to store elements of the sub-row

                # Iterate over each element of the row
                for i in range(n):
                    if(i!=col): # Exclude the current column from the subrow
                        
                        # Append the element to the sub-row if it's not in the current column
                        sub_row.append(matrix[row][i])
                        
                # Append the sub-row to the sub-matrix
                sub_matrix.append(sub_row)
            # Compute determinant of the submatrix recursively
            det+=sign*matrix[0][col]*determinant(sub_matrix)
            
            sign*=-1 # Chnage the sign for cofactor expansion

        return det

# User prompt number of rows
rows = int(input('Enter the number of rows:'))

# Empty list to store user input elements 
A=[]

# User prompt elements of matrix
print('Enter elements of matrix:')
for i in range(rows):
    row = [int(element) for element in input ().split()]
    A.append(row)

# Function call to compute determinent
result=determinant(A)

# Dispaly output
print('Determinant of matrix is:\n',result)

Enter the number of rows: 3


Enter elements of matrix:


 3 7 1
 2 8 5
 3 7 9


Determinant of matrix is:
 80
